### PR TITLE
1.16.3

### PR DESCRIPTION
**Pull request by najlitarvan**
Here i am sending the json for wyrmroost heavy use of comments so it is easier to tweak stuff later.
[wyrmroost.txt](https://github.com/MercuriusXeno/Goo/files/5556125/wyrmroost.txt)

### CODE REVIEW

**Comment by OrionDevelopment** [comment]
This is not the place where this goes.
Addtionally this PR targets the wrong branch,

**Comment by OrionDevelopment** [comment]
You will need to go to the GooForMods github repo and add your values there.

**Comment by najlitarvan** [comment]
could i ask for a link

**Comment by OrionDevelopment** [comment]
https://github.com/MercuriusXeno/GooForMods

**Pull request closed without merging**
